'use client';
import { Truck } from 'lucide-react';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table';
import { useSalesOrdersQuery } from '@/queries/sales-order.queries';
function money(v: unknown) { return `${Number(v ?? 0).toLocaleString()} ETB`; }
export default function Page() { const q = useSalesOrdersQuery({ per_page: 100, status: 'dispatched' }); const rows = q.data?.data ?? []; return <div className="space-y-6"><div><h1 className="text-2xl font-semibold">Delivery Notes</h1><p className="text-sm text-muted-foreground">Dispatched orders ready for delivery note printing and physical dispatch control.</p></div><Card><CardHeader><CardTitle className="flex items-center gap-2"><Truck className="h-5 w-5"/>Generated from dispatched sales orders</CardTitle></CardHeader><CardContent><Table><TableHeader><TableRow><TableHead>Order</TableHead><TableHead>Customer</TableHead><TableHead>Warehouse</TableHead><TableHead>Delivery date</TableHead><TableHead>Total</TableHead><TableHead>Status</TableHead><TableHead className="text-right">Action</TableHead></TableRow></TableHeader><TableBody>{q.isLoading ? <TableRow><TableCell colSpan={7}>Loading delivery notes...</TableCell></TableRow> : rows.length === 0 ? <TableRow><TableCell colSpan={7}>No dispatched sales orders found.</TableCell></TableRow> : rows.map((r) => <TableRow key={r.id}><TableCell>{r.order_number ?? r.id}</TableCell><TableCell>{r.customer?.name ?? r.customer_id}</TableCell><TableCell>{r.warehouse?.name ?? r.warehouse_id}</TableCell><TableCell>{r.delivery_date ?? '—'}</TableCell><TableCell>{money(r.total)}</TableCell><TableCell><Badge variant="outline">{r.status}</Badge></TableCell><TableCell className="text-right"><Button size="sm" variant="outline" onClick={() => window.print()}>Print page</Button></TableCell></TableRow>)}</TableBody></Table></CardContent></Card></div>; }
